[package]
name = "birbs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
currycompose = "0.1.0"
currying = "0.1.0"